version: "3.3"

services:
  iomhaigh-db:
    image: "mysql:5.7"
    container_name: iomhaigh-db
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: iomhaigh
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  iomhaigh-api:
    build: 
        context: /iomhaigh-api/iomhaigh-api/
        dockerfile: Dockerfile
    container_name: iomhaigh-api
    environment:
      - DB_SERVER=iomhaigh-db
      - MYSQL_DATABASE=iomhaigh
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    ports:
      - 51394:51394
    links:
      - iomhaigh-db

  iomhaigh-gui:
    build: 
        context: /iomhaigh-gui/
        dockerfile: Dockerfile
    container_name: iomhaigh-gui
    ports:
      - 80:80
    links:
      - iomhaigh-api


volumes:
  dbdata:
