version: 2
orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.0.0

jobs:
  build:
    working_directory: ~/circle-ci
    docker:
      - image: cimg/base:2020.01
      
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Does docker even exist
          command: docker -v
          
      - run:
          name: Build docker gui
          command: docker-compose build iomhaigh-gui

      - run:
          name: Build docker api
          command: docker-compose build iomhaigh-api

      - run:
          name: Docker up
          command: docker-compose up -d

    deploy_project:
      executor: aws-cli/default
      steps:
        - attach_workspace:
            at: .
        - aws-cli/setup:
            profile-name: default
        - run:
            name: Upload file to S3
            command: aws s3 sync ./dist/ s3://circle-ci-s3-deploy --delete

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          dockerfile: <my-Docker-file>
          path: <path-to-my-Docker-file>
          profile-name: <my-profile-name>
          repo: ${MY_APP_PREFIX}
          tag: '${CIRCLE_SHA1}' 
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image # only run the deployment job once the build and push image job has completed
          family: '${MY_APP_PREFIX}-service'
          cluster-name: '${MY_APP_PREFIX}-cluster'
          container-image-name-updates: 'container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}'
