version: 2
jobs:
  build:
    working_directory: ~/circle-ci
    docker:
      - image: docker:17.05.0-ce-git
      
    steps:
      - checkout
      - setup_remote_docker
      
      - run:
          name: Build docker
          command: |
            docker-compose build iomhaigh-api iomhaigh-gui

      - run:
          name: Docker up
          command: |
            docker-compose up
