version: 2
jobs:
  build:
    working_directory: ~/circle-ci
    docker:
      - image: docker:17.05.0-git
      
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install curl
          command: apk update && apk add curl curl-dev bash

      - run:
          name: Does docker even exist
          command: docker -v
          
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.25.3/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build docker
          command: docker-compose build iomhaigh-api iomhaigh-gui

      - run:
          name: Docker up
          command: docker-compose up
