version: 2
jobs:
  build:
    working_directory: ~/circle-ci
    docker:
      - image: cimg/base:2020.01
      
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Does docker even exist
          command: docker -v
          
      - run:
          name: Build docker gui
          command: docker-compose build iomhaigh-gui

      - run:
          name: Build docker api
          command: docker-compose build iomhaigh-api

      - run:
          name: Docker up
          command: docker-compose up -d
