version: 2
orbs:
  aws-cli: circleci/aws-cli@0.1.18

jobs:
  build:
    working_directory: ~/circle-ci
    docker:
      - image: cimg/base:2020.01
      
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Does docker even exist
          command: docker -v
          
      - run:
          name: Build docker gui
          command: docker-compose build iomhaigh-gui

      - run:
          name: Build docker api
          command: docker-compose build iomhaigh-api

      - run:
          name: Docker up
          command: docker-compose up -d

    deploy_project:
      executor: aws-cli/default
      steps:
        - attach_workspace:
            at: .
        - aws-cli/setup:
            profile-name: default
        - run:
            name: Upload file to S3
            command: aws s3 sync ./dist/ s3://circle-ci-s3-deploy --delete

workflows:
  version: 2
  build:
    jobs:
      - build_project:
          filters:
              branches:
                ignore: /.*/
              tags:
                only: /.*/

      - deploy_project:
          requires:
            - build_project
          context: iomhaigh-aws-context
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
